main:
  - identifier: search
    weight: 99
    params:
      action: appearance
  - name: Home
    identifier: menu.home
    url: /
    weight: 1
  - name: Samples
    identifier: menu.samples
    url: /#samples
    weight: 2
  - name: FAQ
    identifier: menu.faq
    url: /faq/
    weight: 3
  - name: About Us
    identifier: menu.about_us
    url: /about/
    weight: 4
  - identifier: contact
    name: Contacts
    url: /contact/
    weight: 5
# TOP BAR
topbar:
  - weight: 1
    name: Phone
    url: tel:1800-000-000
    pre: <i class='fas fa-2x fa-phone'></i>
  - weight: 2
    name: Email
    url: mailto:info@edeal.com.au
    pre: <i class='fas fa-2x fa-envelope'></i>
  - weight: 3
    name: Facebook
    url: https://facebook.com/edeal-au
    pre: <i class='fab fa-2x fa-facebook'></i>
  - weight: 4
    name: Twitter
    url: https://twitter.com/edeal-au
    pre: <i class='fab fa-2x fa-twitter'></i>
  - weight: 5
    name: Youtube
    url: https://www.youtube.com/channel/edeal-au
    pre: <i class='fab fa-2x fa-youtube'></i>
# Payment methods    
payment_methods:
  - weight: 1
    name: Visa
    pre: <i class='fab fa-cc-visa'></i>
  - weight: 2
    name: Mastercard
    pre: <i class='fab fa-cc-mastercard'></i>
  - weight: 3
    name: PayPal
    pre: <i class='fab fa-cc-paypal'></i>
  - weight: 4
    name: Amex
    pre: <i class='fab fa-cc-amex'></i>
  - weight: 5
    name: Discover
    pre: <i class='fab fa-cc-discover'></i>
